apiVersion: v2
name: go-pkgsite
description: Private pkg.go.dev documentation server
version: 0.1.0
home: https://github.com/mxk/go-pkgsite
sources: [ https://github.com/mxk/go-pkgsite ]

dependencies:
- name: postgresql
  version: ~15.2.5
  repository: oci://registry-1.docker.io/bitnamicharts
