# ingressHost is the Ingress object hostname. The Ingress will not be created if
# this is empty.
ingressHost: localhost

# ingressPath is the Ingress object path prefix.
ingressPath: /

# tlsKey is the PEM-encoded Ingress TLS key.
tlsKey: ''

# tlsCrt is the PEM-encoded Ingress TLS certificate.
tlsCrt: ''

# defaultProxy is the default proxy server used to download public Go modules.
defaultProxy: https://proxy.golang.org

# private defines private repositories. Example:
#   private:
#   - host: internal.example.com
#     username: myusername
#     password: mypassword
private: []

# seed specifies package names passed to seeddb to pre-seed the database.
seed: [std@latest]

# athensVersion is the gomods/athens Docker image tag:
# https://hub.docker.com/r/gomods/athens/tags
athensVersion: v0.14.0

postgresql:
  primary:
    resources:
      requests:
        memory: 8Gi
        cpu: 2
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Delete
      whenDeleted: Delete
