{{- if .Values.ingressHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "go-pkgsite.labels" . | nindent 4 }}
spec:
  {{- if .Values.tlsKey }}
  tls:
  - hosts: [{{ .Values.ingressHost }}]
    secretName: {{ .Release.Name }}
  {{- end }}
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - path: {{ required "Must specify ingressPath" $.Values.ingressPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-pkgsite
            port: {name: http}
{{- end }}
