kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "go-pkgsite.labels" . | nindent 4 }}
data:
  ATHENS_GONOSUM_PATTERNS: {{ include "go-pkgsite.ATHENS_GONOSUM_PATTERNS" . | b64enc | quote }}
  ATHENS_DOWNLOAD_MODE: {{ include "go-pkgsite.ATHENS_DOWNLOAD_MODE" . | b64enc | print "custom:" | b64enc | quote }}
  .netrc: {{ include "go-pkgsite.netrc" . | b64enc | quote }}
  gitconfig: {{ include "go-pkgsite.gitconfig" . | b64enc | quote }}
  {{- if .Values.tlsKey }}
  tls.key: {{ .Values.tlsKey | b64enc | quote }}
  tls.crt: {{ required "Must specify tlsCrt" $.Values.tlsCrt | b64enc | quote }}
  {{- end }}
