kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "go-pkgsite.labels" . | nindent 4 }}
{{- if .Values.tlsKey }}
data:
  tls.key: {{ .Values.tlsKey | b64enc | quote }}
  tls.crt: {{ required "Must specify tlsCrt" $.Values.tlsCrt | b64enc | quote }}
{{- end }}
stringData:
  .netrc: |
    {{- range .Values.private }}
    machine {{ .host }}{{ with .username }} login {{ . }}{{ end }}{{ with .password }} password {{ . }}{{ end }}
    {{- end }}

  {{- with .Values.seed }}
  # Seed contents aren't secret, but this avoids having a separate ConfigMap
  seed.txt: |
    {{- range . }}
    {{ . }}
    {{- end }}
  {{- end }}
