apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "go-pkgsite.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "go-pkgsite.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    targetPort: http
