apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-athens
  labels:
    {{- include "go-pkgsite.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "go-pkgsite.selectors" . | nindent 4 }}
    app.kubernetes.io/component: athens
  ports:
  - {name: http, port: 80, targetPort: http}
